export const BackgroundValues = [
  { id: 1, value: 'apple-1.jpg' },
  { id: 2, value: 'apple-2.jpeg' },
  { id: 3, value: 'apple-3.jpg' },
  { id: 4, value: 'apple-4.jpg' },
  { id: 5, value: 'apple-5.jpg' },
  { id: 6, value: 'apple-6.jpg' },
  { id: 7, value: 'apple-7.jpg' },
  { id: 8, value: 'apple-8.jpg' },
  { id: 9, value: 'apple-9.jpg' },
  { id: 10, value: 'apple-10.jpg' },
  { id: 11, value: 'apple-11.jpeg' },
  { id: 12, value: 'apple-12.jpeg' },
  { id: 13, value: 'apple-13.jpeg' },
  { id: 14, value: 'apple-14.jpg' },
] as const;
